### ISSUE TITLE
Apply after and before using a yml file

### ISSUE THREAD

**Issue by rranelli** [PragTob/after_do#14]
I have been using `after_do` in a project and we thought of a nice way to apply "aspects" to many classes in a non-intrusive way.

The main idea is to write a `.yml` file like this:

```yml
aspects:
  - name: Logging
    klass: LoggingAspect
    description: This aspects provides basic method logging
    advices:
      - name: method_log
        targets:
          - klass: Bundle
            target_methods:
              - initialize
```

There is a `Loader` class that reads this file and applies the rules defined at `LoggingAspect#method_log` to `Bundle#initialize`. This config can be expanded to apply many other "advices" to many other methods.

Would you guys be interested in incorporating this kind of functionality?
I would gladly send you a PR =). 

Otherwise, is it Ok for me to create another gem (say, after_do_rails) that bundles this configuration together for rails apps?

Thank you!
